### ISSUE TITLE
Jobs Limit doesn't get saved when adding subscription levels

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-wp-job-manager#1]
When creating a new subscription, the Jobs Limit value doesn't get saved. It's bails [here](https://github.com/restrictcontentpro/rcp-wp-job-manager/blob/2.1/rcp-wp-job-manager.php#L175).

Appears to happen because `jobs` isn't available in the data [here](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.4.11/includes/class-rcp-levels.php#L248).

**Comment by pippinsplugins** [comment]
Let's get it fixed :+1:
