### ISSUE TITLE
Users on free subscriptions can't post jobs

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-wp-job-manager#10]
Maybe this is more of an enhancement based on the description of the plugin _("Limit job submission to paid subscribers")_ but I had one customer who wanted members of free subscription levels to be able to post jobs.

**Comment by pippinsplugins** [comment]
Looks like we can fix this by replacing `rcp_is_active()` with `$member->can_access()`.

**Comment by nosegraze** [comment]
PR: #11

This PR lets people set up restrictions on the "Submit Job" page using the normal "Restrict this content" meta box and uses that to determine whether someone has permission to post jobs and view resumes (using `$member->can_access()`). If the page is unrestricted (as it very well may be since it wasn't required before) then it falls back to `rcp_is_active()`.
