### ISSUE TITLE
Update plugin author name and URL

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-wp-job-manager#20]
Name: `Sandhills Development, LLC`
URL: `https://sandhillsdev.com`

**Comment by mihaijoldis** [comment]
@nosegraze should we change the plugin name too perhaps ?
Its currently RCP - WP Job Manager Bridge and its not showing in the Plugins list like all our add-ons after the main RCP plugin ?

https://www.screencast.com/t/sqmROIM7N

**Comment by nosegraze** [comment]
@mihaijoldis We can create a new issue to consider it, but let's not actually change it just yet. Someone (was it Tyler or Kyle? don't remember) has been doing research on .org listings and might be worthwhile to discuss with them before contemplating a major change like this.
