### ISSUE TITLE
Allow for 0 max jobs to disable submissions

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-wp-job-manager#6]
`0` max jobs seems to work as unlimited right now due to:

```
if( $max_jobs >= 1 && $submitted >= $max_jobs ) {
	$at_limit = true;
}
```

0 should be allowed to disable submissions entirely, and something else (like a super high number) for unlimited submissions.

Similarly, `save_jobs_input` needs looking at, as it doesn't currently allow you to actually delete a value due to:

```
if( empty( $_POST['jobs'] ) ) {
	return;
}
```

**Comment by nosegraze** [comment]
PR: #7

**Comment by pippinsplugins** [comment]
PR looks great to me.

@mindctrl Good with this? If so could you please merge and deploy the update to .org?

@nosegraze I need to get you added as a committer on .org. What's your username?

**Comment by nosegraze** [comment]
@pippinsplugins It's nosegraze.
